import React from 'react'

const TextEditor = () => {
  return (
    <div>
        <div className='w-full max-w-md bg-[#1a1a1a] rounded-xl p-6 text-white'>
            <p className='leading-relaxed'>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab placeat voluptates id, deleniti explicabo sint quod dignissimos iusto aperiam autem recusandae error tempora expedita repellendus facilis ea ipsum! Harum hic repellendus ratione odit iste quae cum aut at mollitia sequi aliquid consectetur praesentium doloremque eveniet dolorem sunt recusandae nulla iusto accusantium, ipsum quia dicta maiores quibusdam culpa. Quia eaque et magnam quam sit porro, odio corrupti quis maiores eos repellat officiis facere? Eaque nihil mollitia enim? Perspiciatis cupiditate nesciunt laudantium, repellat explicabo quasi odit pariatur odio dignissimos autem mollitia distinctio eos. Illo illum ipsam aliquam amet incidunt eius, sequi quos blanditiis laborum voluptate aliquid numquam autem, assumenda architecto, error nesciunt. Soluta in veniam earum ipsa nesciunt quidem exercitationem fugiat sapiente magnam, suscipit ab ad natus. Eum accusantium sapiente, amet voluptatum ea similique ut vitae autem tenetur odit totam. Odio iure, accusantium quibusdam voluptas dolorem magnam eos? Enim sit dolorem porro sapiente beatae voluptatum similique ex ducimus. Quas sunt quisquam aliquam dicta voluptate esse deleniti harum! Laboriosam, impedit pariatur, deleniti minus omnis laudantium earum reiciendis voluptate perspiciatis, sed perferendis excepturi natus facere voluptates provident ipsam suscipit fugit? Nemo quidem consectetur blanditiis voluptas debitis beatae accusantium! Doloribus consectetur aspernatur mollitia sequi ut.
            </p>
            <p className='leading-relaxed mt-4'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat voluptatem vero tenetur laudantium saepe sed minus mollitia perspiciatis dicta aspernatur. Quaerat dignissimos vero dolore similique. Nisi architecto dolorum id! Sunt eius culpa, delectus fugiat error corporis expedita iure asperiores quisquam eligendi, est optio tenetur numquam quam eum vel ipsam molestias sequi mollitia. Dolores fugit magni itaque ut quidem possimus debitis autem, error architecto asperiores fuga in ea voluptate ex ipsum dignissimos aperiam. Alias, quia! Fugiat facilis cum ipsam ipsum possimus iusto libero molestiae ratione quis placeat iste quibusdam inventore, saepe aspernatur consectetur ducimus rerum officiis quidem. Aperiam maxime quisquam atque labore et aliquid totam, soluta ad blanditiis modi assumenda necessitatibus nostrum. Dicta, porro qui? Sed corporis corrupti tempore? Ea quos voluptatum iure cumque molestias aliquid placeat id magnam quas quasi deleniti blanditiis similique eum, officia, quis repellendus error, quo veniam. Id eveniet facilis, aspernatur veniam possimus incidunt odit commodi ipsum sequi hic molestias reiciendis quibusdam provident. Magni, provident id. Quasi modi dolore laborum officia, repellendus architecto inventore nostrum aperiam dolorum, dicta, quae cupiditate eos eum consequuntur aliquid maiores delectus repudiandae recusandae corporis. Voluptas amet dolor nihil maiores? Velit, accusantium veniam fuga deserunt mollitia dicta aliquid. Blanditiis eos animi autem consequuntur!
            </p>
        </div>
    </div>
  )
}

export default TextEditor